### ISSUE TITLE
Thank you for your contribution! But i still understand how to train faster-rcnn and detect use the project,can u tell more detail

### ISSUE THREAD

**Issue by abner2015** [D-X-Y/caffe-faster-rcnn#1]
Thank you for your contribution! But i still understand how to train faster-rcnn and detect use the project,can u tell more detail

**Comment by D-X-Y** [comment]
Hi, I update the ReadMe adding more details.
It may be better to trace what the examples/FRCNN/zf/train_frcnn.sh does.
You should prepare dataset and pre-train model files in the right place.
The prototxt for network definition and VOC2007 image list are already in this repo.

**Comment by abner2015** [comment]
now, i not seen the update. I have another question is whether this project can be compiled into a dynamic link library. THK

**Comment by D-X-Y** [comment]
There are two branches, try "git checkout dev" into dev branch.
This project is based on the official caffe code, and the caffe project can be compiled into a dynamic link library.
After compile, see libcaffe.so

**Comment by abner2015** [comment]
Thank you for your answer. 
As far as I know, faster-rcnn also has python layer , How does this version deal with python layer?
Whether i need  to install python and add python path ?
If I have trained the py-faster-rcnn  model, can I directly use it on the windows test, or made a dll?

**Comment by D-X-Y** [comment]
This version is a re-implement of py-faster-rcnn, which converts the python layer into C++ layer.
This code does not require to deal with python layer.
As the python layer for faster-rcnn does not have trainable parameters, the trained model can be directly used in this version.
But you may need to change the test prototxt, make sure that layer name and type is right.
I'm not familiar with caffe on windows and dll, as it's ok for linux, I thinks it will be ok on windows.

**Comment by abner2015** [comment]
It is cool!
Ask a stupid question, how to compile under the window system.

**Comment by D-X-Y** [comment]
I never try caffe in the Windows.
Maybe you could google it.

**Comment by abner2015** [comment]
Caffe has an official support for the version of caffe-windows.
If your faster-rcnn integrated into caffe-windows  then I know how to use it.
I do not know if it's complicated that add rpn layer and python layer rewriter c++

**Comment by D-X-Y** [comment]
Seems only need to copy FRCNN directories into caffe-windows and make some change on the caffe.proto

**Comment by giddyyupp** [comment]
Just to clarify, you also need to update **cmake** files accordingly, after copying all FRCNN related files. 
also json_parser gives an error, since in windows it can't parse anchors correctly if you put them in a matrix form. you just put all numbers in a single line then everything is fine. 
@D-X-Y you could put these information into the main page and add windows tag. i able to build it under vs2015, and runs fine by now. 
thanks for the code btw.
