### ISSUE TITLE
faster_caffe_compiler

### ISSUE THREAD

**Issue by xwater8** [D-X-Y/caffe-faster-rcnn#10]
@D-X-Y 我已經把frcnn_proposal_layer.cu解掉了，雖說不確定解法對不對，解法是將<cub.cuh>往下搬就編譯過去了，也覺得有點莫名其妙....
![image](https://cloud.githubusercontent.com/assets/15085015/24690990/5e79b04e-1a03-11e7-9f8b-7e1a7ae9af1d.png)
現在碰到另外一個問題，在準備做nms的時候會碰到vector超出界線，問題是出在這裡(frcnn_proposal_layer.cpp)
![image](https://cloud.githubusercontent.com/assets/15085015/24691033/bf5eb058-1a03-11e7-94cb-269dddf8b275.png)
anchor和sorted_vector上面有做一個erase的動作，讓她們只剩下6000個，但是我這邊得到的index卻會超出這個範圍。
我的問題是，這是因為我的frcnn_porposal_layer.cu沒有弄好才發生這種情況，還是說這真的是一個當初寫程式上少考慮到的問題？

剛剛看了一下frcnn_porposal_layer.cu是不是沒有實作？直接交由CPU來處理，因為看到預設的
void FrcnnProposalLayer<Dtype>::Forward_gpu(const vector<Blob<Dtype> *> &bottom,
    const vector<Blob<Dtype> *> &top) {
  Forward_cpu(bottom, top);
  return ;

#if 0
nms.....
#endif
}
#if 0裡面的是都可以正常使用的，還是說還沒實作完成？

**Comment by xwater8** [comment]
okay! 已經全部解決了，謝謝幫忙。
GPU Code部分的確是正常的
不過在Windows上面CUDA要使用特定版本8.0.44才能正常編譯cub
可以參考這篇：
https://github.com/dmlc/mxnet/issues/5041
---------------------------------------------------------
frcnn_proposal_layer.cpp的那個bug請作者幫忙修復一下
在144行的部分
anchors[cur_i] 他有可能會存取超出6000的部分，但是你在上面先將anchors刪除到只剩下6000，因此會出現問題，或許是Ubuntu-g++和Windows-VC++的Vector-Erase實作方法不一樣，Ubuntu上面Erase以後還是可以存取到資料，但是Windows上面的不行。

建議作者將anchors.erase(anchors.begin()+n_anchors, anchors.end());直接註解掉

這個issue請作者幫忙關閉吧！

**Comment by D-X-Y** [comment]
好的，感谢这个bug的建议，已经修改，#if 0里面应该是我印象里应该是没有问题的，之前切换到cpu代码可能是为了debug，我会尽快检查下，确认正确。
