### ISSUE TITLE
py-faster-rcnn-models

### ISSUE THREAD

**Issue by xwater8** [D-X-Y/caffe-faster-rcnn#11]
請問一下，使用py-faster-rcnn的faster_rcnn_alt_opt.sh 所Train出來的ZF Model是不是沒辦法拿來Demo，我用之前在Ubuntu上Train好的Model，但是我的TestVideo上面一個框框都沒有，是不是只能使用end2end training的方式才能使用你的C++ Code Demo??

**Comment by xwater8** [comment]
再問一個問題，我的Model都是使用py-faster-rcnn訓練的
我用VGG end2end訓練，直接用你的C++ demo看起來沒有問題
我用ZF end2end訓練，用你的C++ demo他的Box會不正確，我用convert_model.py處理完model以後就正常了
請問：我應該是兩個Model都要經過convert_model.py的處理嗎？ 還是只有ZF要經過convert_model.py的處理？

**Comment by D-X-Y** [comment]
理论上用 py-faster-rcnn end2end训练的模型是不需要convert_model 的，因为它里面已经做了这一波转换了，可以直接拿来用我这里的C++代码测试，但因为py faster rcnn的输入和我这里用C++读图片resize后的结果会有一些区别，所以最终结果会有一点点不同
