### ISSUE TITLE
pre-trained model repository error

### ISSUE THREAD

**Issue by had3i** [D-X-Y/caffe-faster-rcnn#12]
Hi
I have problem in downloading pre trained faster RCNN model in following address.
https://people.eecs.berkeley.edu/~rbg/faster-rcnn-data/imagenet_models.tgz

the repository is out of reach,

**Comment by D-X-Y** [comment]
You can try this script https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/scripts/fetch_faster_rcnn_models.sh
To download a pre-trained model.
