### ISSUE TITLE
Meet Error: selected_num > 0 (-1 vs. 0)

### ISSUE THREAD

**Issue by bluekingdom** [D-X-Y/caffe-faster-rcnn#13]
I met an error when run the train script in examples/FRCNN/zf/train_frcnn.sh. log show below:
`I0414 11:50:26.168201 27156 solver.cpp:280] Learning Rate Policy: step
I0414 11:50:26.264729 27156 frcnn_anchor_target_layer.hpp:94] Info_Stds_Means_AvePos : COUNT : 23
I0414 11:50:26.264750 27156 frcnn_anchor_target_layer.hpp:95] STDS   : 0.0124143, 0.142521, 0.0744314, 0.40446
I0414 11:50:26.264778 27156 frcnn_anchor_target_layer.hpp:96] MEANS  : 0.00592739, 0.0176122, 0.0154362, 0.0769088
I0414 11:50:26.264783 27156 frcnn_anchor_target_layer.hpp:98] num_positive ave : 23
I0414 11:50:26.264788 27156 frcnn_anchor_target_layer.hpp:99] num_negitive ave : 233
F0414 11:50:26.271618 27156 frcnn_proposal_layer.cu:222] Check failed: selected_num > 0 (-1 vs. 0) 
`
Can anyone give me some tips? thx~

**Comment by D-X-Y** [comment]
Try to remove the frcnn_proposal_layer.cu code and use the CPU code, frcnn_propoasl_layer.cpp，
I'm checking the cuda code of frcnn proposal layer,

**Comment by bluekingdom** [comment]
I found it may caused by GPU memory. Train log change like this when i decrease batch size in voc_config.json.

`
I0414 14:52:05.112727 30277 frcnn_anchor_target_layer.hpp:94] Info_Stds_Means_AvePos : COUNT : 23
I0414 14:52:05.112761 30277 frcnn_anchor_target_layer.hpp:95] STDS   : 0.0124143, 0.142521, 0.0744314, 0.40446
I0414 14:52:05.112792 30277 frcnn_anchor_target_layer.hpp:96] MEANS  : 0.00592739, 0.0176122, 0.0154362, 0.0769088
I0414 14:52:05.112797 30277 frcnn_anchor_target_layer.hpp:98] num_positive ave : 23
I0414 14:52:05.112802 30277 frcnn_anchor_target_layer.hpp:99] num_negitive ave : 41
F0414 14:52:07.725273 30277 frcnn_nms_kernel.cu:105] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
`

**Comment by D-X-Y** [comment]
So did you fix it now?

**Comment by bluekingdom** [comment]
@D-X-Y I change a mechine with large GPU memory and then this error did not appear again. thx for your response~
