### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by had3i** [D-X-Y/caffe-faster-rcnn#14]
Hi
when I run make runtest I get the following error

LayerFactoryTest/0.TestCreateLayer
F0415 10:13:55.910223 19378 frcnn_proposal_layer.hpp:48] Check failed: error == cudaSuccess (17 vs. 0)  invalid device pointer
*** Check failure stack trace: ***
    @     0x7f0090b6092d  google::LogMessage::Fail()
    @     0x7f0090b627e0  google::LogMessage::SendToLog()
    @     0x7f0090b604f2  google::LogMessage::Flush()
    @     0x7f0090b631fe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f008ba24bee  boost::detail::sp_counted_impl_p<>::dispose()
    @           0x8b0d92  caffe::LayerFactoryTest_TestCreateLayer_Test<>::TestBody()
    @           0x941253  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9380aa  testing::Test::Run()
    @           0x9381f8  testing::TestInfo::Run()
    @           0x938305  testing::TestCase::Run()
    @           0x93a988  testing::internal::UnitTestImpl::RunAllTests()
    @           0x93ac73  testing::UnitTest::Run()
    @           0x469cff  main
    @     0x7f008ad403f1  (unknown)
    @           0x47144a  _start
Makefile:533: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)

any idea?

**Comment by D-X-Y** [comment]
I did not write official test code for frcnn layers.
It does not need to run 'runtest'

**Comment by guweixin** [comment]
Found the answer in this pull request: #24
