### ISSUE TITLE
Check failed: registry.count(type) == 0 (1 vs. 0) Layer type Convolution already registered 

### ISSUE THREAD

**Issue by had3i** [D-X-Y/caffe-faster-rcnn#15]
Hi,
I'm trying to load in test phase a network configuration which has a memory data layer first and then a convolution layer. The MemoryData layer creation succeeds, But the convolution layer's creation fails .
the printed error is:
`F0415 12:58:03.314304 26017 layer_factory.hpp:69] Check failed: registry.count(type) == 0 (1 vs. 0) Layer type Convolution already registered.`
`*** Check failure stack trace: ***`

any idea how to solve the problem?

**Comment by D-X-Y** [comment]
Sorry, I never meet this problem.. Do you define convolution layer twice?
