### ISSUE TITLE
Train Error: Floating point exception

### ISSUE THREAD

**Issue by bluekingdom** [D-X-Y/caffe-faster-rcnn#17]
Error log show below: 

    *** Aborted at 1493105015 (unix time) try "date -d @1493105015" if you are using GNU date ***

    PC: @     0x7fd334914fe6 caffe::SGDSolver<>::GetLearningRate()

    *** SIGFPE (@0x7fd334914fe6) received by PID 4218 (TID 0x7fd3369759c0) from PID 881938406; stack trace: ***

    @     0x7fd332990d40 (unknown)
    @     0x7fd334914fe6 caffe::SGDSolver<>::GetLearningRate()
    @     0x7fd33491551f caffe::SGDSolver<>::ApplyUpdate()
    @     0x7fd334943a10 caffe::Solver<>::Step()
    @     0x7fd334942a37 caffe::Solver<>::Solve()
    @           0x41a24a train()
    @           0x41c4f9 main
    @     0x7fd33297bec5 (unknown)
    @           0x418c59 (unknown)
    @                0x0 (unknown)
    Floating point exception

Can anyone give some tip? thx~

**Comment by D-X-Y** [comment]
Can you give more details, like your solver file and training scripts?

**Comment by bluekingdom** [comment]
@D-X-Y thx~
I train res101 net with voc dataset and script is unchanged. Training script run in Ubuntu 14.04 and 12G GPU.

**Comment by D-X-Y** [comment]
According to the stack, it seems something wrong happens in GetLearningRate function.
But I never change this part of code...
Maybe your could search on https://groups.google.com/forum/#!forum/caffe-users

**Comment by bluekingdom** [comment]
@D-X-Y There are no problem when training with zf / vgg net. It is possible the error occur from GPU momery? Do you train resnet with multi-gpu?

**Comment by D-X-Y** [comment]
Yes, I have trained res101 several months ago on single gpu.
Multi-gpu will cost extra gpu memories.
