### ISSUE TITLE
Compiling Issue with FRCNN_API

### ISSUE THREAD

**Issue by WaldoFF** [D-X-Y/caffe-faster-rcnn#18]
Hi

I'm having some issues compiling and running the demos. I did a clean install of Ubuntu 14.04 and I'm able to compile Caffe and py-faster-rcnn without issue. So I'm assuming my system setup is correct, as is the Makefile.config (attached). The output from cmake is attached as well. 

[cmake Output.zip](https://github.com/D-X-Y/caffe-faster-rcnn/files/978489/cmake.Output.zip)
[Makefile.config.zip](https://github.com/D-X-Y/caffe-faster-rcnn/files/978479/Makefile.config.zip)

The error I receive while compiling is listed below:

$make
...
[ 98%] Building CXX object examples/CMakeFiles/demo_frcnn_api.dir/FRCNN/demo_frcnn_api.cpp.o
Linking CXX executable FRCNN/demo_frcnn_api
CMakeFiles/demo_frcnn_api.dir/FRCNN/demo_frcnn_api.cpp.o: In function `main':
demo_frcnn_api.cpp:(.text.startup+0x686): undefined reference to `FRCNN_API::Detector::Set_Model(std::string&, std::string&)'
demo_frcnn_api.cpp:(.text.startup+0x7ac): undefined reference to `FRCNN_API::Detector::predict(cv::Mat const&, std::vector<caffe::Frcnn::BBox<float>, std::allocator<caffe::Frcnn::BBox<float> > >&)'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/FRCNN/demo_frcnn_api] Error 1
make[1]: *** [examples/CMakeFiles/demo_frcnn_api.dir/all] Error 2
make: *** [all] Error 2

I'm not to familiar with cmake, but did some digging and could not find any issue with the linking . Removing the the files in the example folder allows the compilation to complete.

Any help would be greatly appreciated.

System configuration
Operating system: Ubuntu 14.04 LTS
Compiler: gcc V4.8.4 with cmake
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.1
OpenCV: 2.4.13 built from source
Python: 2.76

**Comment by D-X-Y** [comment]
I also did not use cmake, do you try to directly type make under the $caffe_root path?

**Comment by D-X-Y** [comment]
CMAKE may need some cmake files in the corresponding dirs, which I did not write.

**Comment by WaldoFF** [comment]
Thanks. That solved my issue after some reconfig to get make working. I assumed you were using the same procedure as normal Caffe to build.
