### ISSUE TITLE
runtime error about demo_frcnn.sh

### ISSUE THREAD

**Issue by liujian883** [D-X-Y/caffe-faster-rcnn#2]
Hi,  I cloned the dev branch (commit ID  c2cf0c7),I compiled the code with only CPU mode.
the I ran the demo_frcnn.sh. It seems like Json file read error.

<<<<<<<<<<<<<<<<<<<<<<<<
ehigh@hgsv:~/work/caffe-faster-rcnn-dev/examples/FRCNN$ sh demo_frcnn.sh 
 is empty, default is 0
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::json_parser::json_parser_error> >'
  what():  <unspecified file>: read error
*** Aborted at 1488247761 (unix time) try "date -d @1488247761" if you are using GNU date ***
PC: @     0x7fea8c40af79 (unknown)
*** SIGABRT (@0x3e80000d037) received by PID 53303 (TID 0x7fea8e17ba40) from PID 53303; stack 
Aborted (core dumped)
<<<<<<<<<<<<<<<<<<<<<<<<

because I have not GPU,so I modified the shell script（remove --gpu option）:
<<<<<<<<<<<<<<<<<<<<<<<<
if [ ! -n "$1" ] ;then
    echo "$1 is empty, default is 0"
    gpu=0
else
    echo "use $1-th gpu"
    gpu=$1
fi

BUILD=../../build/examples/FRCNN/demo_frcnn_api.bin

#$BUILD --gpu $gpu \
$BUILD --model models/FRCNN/vgg16/test.prototxt \
       --weights models/FRCNN/VGG16_faster_rcnn_final.caffemodel \
       --default_c examples/FRCNN/config/voc_config.json \
       --image_dir examples/FRCNN/images/  \
       --out_dir examples/FRCNN/results/
<<<<<<<<<<<<<<<<<<<<<<<<                                      

can you help me ?thank you!

**Comment by liujian883** [comment]
the path problem.

**Comment by HJiahu** [comment]
add try ..catch in parse_json_config for ... boost::property_tree::read_json (ifs, pt);... , 
exception shows:  parse json failed: <unspecified file>(49): invalid code sequence
erase all line breaks in json file about line 49, everything is OK.
