### ISSUE TITLE
using gpu to forward at proposal layer

### ISSUE THREAD

**Issue by twmht** [D-X-Y/caffe-faster-rcnn#21]
Hi,

I am curios about the implementation about `src/caffe/FRCNN/frcnn_proposal_layer.cu`, where the `forward` is implemented as the cpu version.

```
template <typename Dtype>
void FrcnnProposalLayer<Dtype>::Forward_gpu(const vector<Blob<Dtype> *> &bottom,
    const vector<Blob<Dtype> *> &top) {
  Forward_cpu(bottom, top);
  return ;
}
```

why not implemented as the gpu version?

thanks!

**Comment by D-X-Y** [comment]
The gpu implementation is commented, because there seems some unknow bugs in the cu code(on windows platform).

**Comment by twmht** [comment]
@D-X-Y 

I am using ubuntu 16.04, so it is ok to uncomment the cuda code when running on linux?

thanks

**Comment by D-X-Y** [comment]
I can not guarantee it, you would better the the c++ code for FrcnnProposalLayer, and the speeds of the whole network for using cu or c++ are close, because FrcnnProposalLayer only takse a small part of the whole network.

**Comment by e2sh83** [comment]
Hi,
I found inference results between FrcnnProposalLayer of CPU and GPU are in differ when everything else is in same(prototxt, caffemodel and etc. I tried this on Ubuntu 14.04). FrcnnProposalLayer GPU sometimes produces some wired results such as min_x/min_y is larger than max_x/min_y. 
The inference time could be also quite huge gap when we use large input like shorter size is 720p and many anchors.

**Comment by twmht** [comment]
@e2sh83 

Did you solve the problem?

**Comment by makefile** [comment]
I met the same situation as @e2sh83 , FrcnnProposalLayer .cu code is AP ~1% less than CPU code. and there have some regressed value exceeds the image boundary. so i change the code in frcnn_api.cpp to clip boundary.

**Comment by twmht** [comment]
@makefile 

Can you share the code you modified?

**Comment by makefile** [comment]
@twmht change code from
```c++
      box[0] = std::max(0.0f, box[0]);
      box[1] = std::max(0.0f, box[1]);
      box[2] = std::min(width-1.f, box[2]);
      box[3] = std::min(height-1.f, box[3]);
```
to
```c++
      box[0] = std::max(0.0f, std::min(box[0], width - 1.f));
      box[1] = std::max(0.0f, std::min(box[1], height - 1.f));
      box[2] = std::max(0.0f, std::min(box[2], width - 1.f));
      box[3] = std::max(0.0f, std::min(box[3], height - 1.f));
```
