### ISSUE TITLE
anchorBox may Error

### ISSUE THREAD

**Issue by xwater8** [D-X-Y/caffe-faster-rcnn#23]
我查了一下原本的py-faster-rcnn的generate_anchor.py
#    anchors =
#
#       -83   -39   100    56
#      -175   -87   192   104
#      -359  -183   376   200 #這邊是寫200
#       -55   -55    72    72
#      -119  -119   136   136
#      -247  -247   264   264
#       -35   -79    52    96
#       -79  -167    96   184
#      -167  -343   184   360

examples/FRCNN/config/voc_config.json

"anchors": "-84, -40, 99, 55,
             -176,  -88,  191,   103,
             -360,  -184,   375,    100,##這邊是否有問題
             -56,   -56,    71,    72,
             -120,  -120,   135,   135,
             -248,  -248,   263,   263,
             -36,   -80,    51,    95,
             -80,   -168,   95,    183,
             -168,  -344,   183,   359",

**Comment by D-X-Y** [comment]
嗯，这里应该有点问题，以pyfaster rcnn为准。多谢指出

**Comment by zhonhel** [comment]
现在这个repo里的voc_config.json还是100。为什么我的本地的repo里变成200了。
是有哪个过程生成了这个voc_config.json吗？

**Comment by D-X-Y** [comment]
config是需要预先定义好的，不是生成的，我中间的某次commit改过这个参数。
