### ISSUE TITLE
Cub library

### ISSUE THREAD

**Issue by RomainDWipsea** [D-X-Y/caffe-faster-rcnn#24]
Hi, 
I can see that frcnn_proposal_layer.cu uses #include <cub/cub.cuh>. 
However I see no other mention of this library. 

Shouldn't we have some FindCUB.cmake in cmake/Modules/ ? 

I'm asking this because I'm trying to get this project to work on windows and I need the cmake environement since i'm using the official windows branch as an example.

I did add a FindCUB.cmake (https://github.com/caffe2/caffe2/blob/master/cmake/Modules/FindCUB.cmake) with the correct PATHS option and these lines in Dependencies.cmake : 
```
  find_package(CUB REQUIRED)
  list(APPEND Caffe_INCLUDE_DIRS PUBLIC ${CUB_INCLUDE_DIR})
```

But then I get some errors with caffe.pb.h when building frcnn_proposal_layer.cu :  

> caffe-faster-rcnn/build/include\caffe/proto/caffe.pb.h(2757): error: expected an identifier

The corresponding line in caffe.pb.h is : 
` static const DimCheckMode STRICT = ParamSpec_DimCheckMode_STRICT;`

At this point, I guess I'm missing something when trying to include cub, but I may be wrong, any clues?

**Comment by samlong-yang** [comment]
I make caffe and get the error: `src/caffe/FRCNN/frcnn_proposal_layer.cu:7:23: fatal error: cub/cub.cuh: No such file or directory. compilation terminated.`
I'm using cuda8.0 and cudnn5.0, what's wrong with the cub.cuh?

**Comment by RomainDWipsea** [comment]
It's actually in the QA section : 

> CUB not found, when compile for GPU version, frcnn_proposal_layer.cu requires a head file <cub/cub.cuh>. CUB is library contained in the official Cuda Toolkit, usually can be found in /usr/local/cuda/include/thrust/system/cuda/detail/. You should add this path in your Makefile.config (try locate ''cub.cuh'' to find cub on your system)

I should have fully read it. Guess it closes the issue.

**Comment by hiperz** [comment]
@RomainDWipsea Hello, I have exactly same error as you, "expected an identifier"
I merged this branch to the official windows branch. Could you tell me how did you fix this error?
