### ISSUE TITLE
OpenCV3 support

### ISSUE THREAD

**Issue by gautamMalu** [D-X-Y/caffe-faster-rcnn#28]
I am using your code in [opendetection](https://github.com/gautamMalu/opendetection) library, That library only support OpenCV3, I am using your caffe for faster rcnn.  As far as I understand it's being used for bbox visualization, If you can point where else you are using opencv in your code, I can make PR for OpenCV 3 support.

**Comment by D-X-Y** [comment]
Sure, very thanks.
The opencv is only used for read input image, in
https://github.com/D-X-Y/caffe-faster-rcnn/blob/dev/src/caffe/FRCNN/frcnn_roi_data_layer.cpp
and
https://github.com/D-X-Y/caffe-faster-rcnn/blob/dev/src/caffe/FRCNN/frcnn_vid_data_layer.cpp 
Also, I'm not sure that whether the caffe version of this branch support OpenCV3, if not , then maybe we should merge the caffe master branch.

**Comment by gautamMalu** [comment]
Please checkout  pull request #29

**Comment by D-X-Y** [comment]
Ok, I will check it in this week
