### ISSUE TITLE
Can this faster rcnn train with multi-gpu

### ISSUE THREAD

**Issue by xuguodong03** [D-X-Y/caffe-faster-rcnn#30]
I am not sure whether this faster rcnn can work with multi-gpu. Though it can run with option '-gpu all', it seems that all the gpus are using the same image.

**Comment by D-X-Y** [comment]
It's ok with multiple gpu, but on each gpu you must make sure that batch size = 1

**Comment by xuguodong03** [comment]
Thanks for your reply.
I add some code to ./src/caffe/layers/base_data_layer.cu to print information about rois. And I didn't revise any code besides this. When I train the net, all the gpus seem to print the same information.  How can this happen?

**Comment by D-X-Y** [comment]
You shuold probably check the random seed that used in each GPU, the random seed in the roi data layer control which image will be sampled for training. And if you explicitly set this seed in roi data parameter, it will be the same on four gpus.

**Comment by xuguodong03** [comment]
Thanks a lot！ The problem was solved.
