### ISSUE TITLE
can not build caffe

### ISSUE THREAD

**Issue by fjfo** [D-X-Y/caffe-faster-rcnn#4]
### Issue summary
I can not "$make all" from this branch.
It seem can not found contrib header file.
When I list "$ls /usr/local/include/opencv2/"
there is no **contrib** folder in this.

### Steps to reproduce
/include/caffe/ACTION_REC/video_data_layer.hpp:21:10: fatal error: 'opencv2/contrib/contrib.hpp' file not found
#include <opencv2/contrib/contrib.hpp>
         ^
1 error generated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/ACTION_REC/video_data_layer.cpp.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

### system configuration
Operating system: MacOS 10.12
Compiler: gcc

**Comment by D-X-Y** [comment]
I install the opencv via homebrew on my MAC.
This header file is in /usr/local/Cellar/opencv/2.4.13/include/opencv2/contrib/
and I can successfully build this version of caffe.

**Comment by fjfo** [comment]
I see,
Seem you use OpenCV 2.4.13, newest one I use is OpenCV 3.2.0 building from source.
I need API opencv 3.2.0 for my project.
What should I do now, downgrade opencv to 2.4.13 and rebuild your caffe?

**Comment by D-X-Y** [comment]
Homebrew can manage different versions of opencv, I think you could install 2.4.13 to rebuild your caffe.
Or you could delete the file ./include/caffe/ACTION_REC and ./src/caffe/ACTION_REC, which are  irrelevant to the Faster RCNN

**Comment by fjfo** [comment]
I just deleted "ACTION_REC" source and header, but in "FRCNN" this error happen again.
I can not deleted "FRCNN" cause' I need these code that why I'm here.
Trying option 1 now (installing 2.4.13 from Brew), not sure it work.
God bless me.

**Comment by D-X-Y** [comment]
Good luck, your project need opencv 3.2 and you need the FRCNN code in the same project?

**Comment by D-X-Y** [comment]
@fjfo The opencv is only required by the image processing, it should be easy to transfer the codes from opencv-2 to opencv-3.

**Comment by fjfo** [comment]
Yes, I need opencv 3.2 and FRCNN in the same project.
Transferring FRCNN to support opencv 3.2 will cost me a lot of time.
I hope you could help me in this task :D 
Thank,

**Comment by D-X-Y** [comment]
Sorry, I'm working on ICCV and might have time to support opencv 3.2 after ICCV due.

**Comment by fjfo** [comment]
hi D-X-Y,
I download and install opencv 2.4.13 ok now.
the issue is gone but I got another:

> CXX/LD -o .build_release/examples/FRCNN/loc_test_frcnn.bin
Undefined symbols for architecture x86_64:
  "FRCNN_API::Detector::predict(cv::Mat const&, std::__1::vector<caffe::Frcnn::BBox<float>, std::__1::allocator<caffe::Frcnn::BBox<float> > >&)", referenced from:
      _main in demo_frcnn_api.o
  "FRCNN_API::Detector::Set_Model(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      _main in demo_frcnn_api.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

> Any idea?

**Comment by D-X-Y** [comment]
It seems the path of dynamic link library is not well settled.
And are you sure that both of the opencv 2 and opencv 3 can be used in the same project?

**Comment by fjfo** [comment]
Thank you,
I removed Examples code  and successful compiled.

I remove opencv 3 because of this issue. =), just use oencv 2.4.13
