### ISSUE TITLE
Can not run demo_frcnn_api.cpp

### ISSUE THREAD

**Issue by fjfo** [D-X-Y/caffe-faster-rcnn#5]
### Issue summary
Can not build and run Demo_frcnn_api.cpp
Error in: **SetModel** function, it require **roi_pool** layer;
`CHECK(this->roi_pool_layer >= 0 && this->roi_pool_layer < layer_names.size());`

### Steps to reproduce
- Build all required library done.
- Download final model with weight from: https://github.com/ShaoqingRen/faster_rcnn
**faster_rcnn_VOC0712_vgg_16layers**
- Run **Demo_frcnn_api.cpp**
with params:
DEFINE_string(model, "faster_rcnn_VOC0712_vgg_16layers/proposal_test.prototxt",
              "The model definition protocol buffer text file.");
DEFINE_string(weights, "faster_rcnn_VOC0712_vgg_16layers/proposal_final", 
              "Trained Model By Faster RCNN End-to-End Pipeline.");
DEFINE_string(default_c, "voc_config.json", 
              "Default config file path.");
DEFINE_string(image_dir, "faster_rcnn_final_model/test_img/",
              "Optional;Test images Dir."); 
### Your system configuration
Operating system: MacOS 10.12
Compiler: clang++

**Comment by D-X-Y** [comment]
The prototxt that you use has only the definition of rpn, the fast rcnn prototxt is also required in the same file.
You can try examples/FRCNN/demo_frcnn.sh and use the weight file from https://github.com/rbgirshick/py-faster-rcnn

If you only need rpn network, try test_rpn

**Comment by fjfo** [comment]
Thank for your help
