### ISSUE TITLE
cannot find -lopencv_dep_cudart on Ubuntu 16.04

### ISSUE THREAD

**Issue by fjfo** [D-X-Y/caffe-faster-rcnn#6]
### Issue summary
Linking CXX shared library ../../lib/libcaffe.so
/usr/bin/ld: cannot find -lopencv_dep_cudart
collect2: error: ld returned 1 exit status
src/caffe/CMakeFiles/caffe.dir/build.make:39173: recipe for target 'lib/libcaffe.so.1.0.0-rc4' failed
make[2]: *** [lib/libcaffe.so.1.0.0-rc4] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

### Steps to reproduce
- cmake ..
- make

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: C++
CUDA version (if applicable): 8.0
CUDNN version (if applicable): 5.1
GPU Gf 1080

**Comment by D-X-Y** [comment]
Try use Makefile.config and make?
It's ok on my Ubuntu 16.04 with cuda8.0 and cudnn v5.1

**Comment by fjfo** [comment]
Another way ti fix these:
- mkdir build & cd build
- cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DOpenCV_DIR=/path/to/opencv-2.4.13/build ..
- make -j8
- make all & install 

Compiled now =) Have fun

**Comment by D-X-Y** [comment]
Thanks for the complement.
