### ISSUE TITLE
training faster rcnn error

### ISSUE THREAD

**Issue by fjfo** [D-X-Y/caffe-faster-rcnn#7]
### Issue summary
Can not train my own dataset with ZF prototxt.
`

- I0318 00:02:50.484649 3165086656 caffe.cpp:248] Starting Optimization
- I0318 00:02:50.484681 3165086656 solver.cpp:279] Solving ZF-Faster-End-To-End
- I0318 00:02:50.484686 3165086656 solver.cpp:280] Learning Rate Policy: step
- I0318 00:02:52.183960 3165086656 frcnn_anchor_target_layer.hpp:94] Info_Stds_Means_AvePos : COUNT : 2
- I0318 00:02:52.183990 3165086656 frcnn_anchor_target_layer.hpp:95] STDS   : 0, 0.0454545, 0, 0
- I0318 00:02:52.184000 3165086656 frcnn_anchor_target_layer.hpp:96] MEANS  : 0.0301278, -0.141544, -0.0746223, -0.727437
- I0318 00:02:52.184007 3165086656 frcnn_anchor_target_layer.hpp:98] num_positive ave : 2
- I0318 00:02:52.184011 3165086656 frcnn_anchor_target_layer.hpp:99] num_negitive ave : 254
- F0318 00:02:52.193294 3165086656 smooth_L1_loss_layer.cpp:54] Not Implemented Yet
- *** Check failure stack trace: ***
-     @        0x108ae8ea8  google::LogMessage::Fail()
-     @        0x108ae831c  google::LogMessage::SendToLog()
-     @        0x108ae887a  google::LogMessage::Flush()
-     @        0x108aebc2f  google::LogMessageFatal::~LogMessageFatal()
-     @        0x108ae918f  google::LogMessageFatal::~LogMessageFatal()
-     @        0x10872c141  caffe::SmoothL1LossLayer<>::Forward_cpu()
-     @        0x10875a2fa  caffe::Layer<>::Forward()
-     @        0x1087f220a  caffe::Net<>::ForwardFromTo()
-     @        0x1087f20f2  caffe::Net<>::Forward()
-     @        0x108806165  caffe::Solver<>::Step()
-     @        0x108805abd  caffe::Solver<>::Solve()
-     @        0x1086c7f2b  train()
-     @        0x1086ca73b  main
-     @     0x7fffb3c29255  start
- examples/FRCNN/zf/train_frcnn.sh: line 6: 77998 Abort trap: 6

`
### Steps to reproduce
usin: train_frcnn.sh with my own dataset

When I look at to the class: smooth_L1_loss_layer.cpp:54
`void SmoothL1LossLayer<Dtype>::Forward_cpu(const vector<Blob<Dtype>*>& bottom,
    const vector<Blob<Dtype>*>& top) {
  NOT_IMPLEMENTED;
}`

What does that mean?

### Your system configuration
Operating system: MacOS 10.12

**Comment by D-X-Y** [comment]
You should train the Faster RCNN on GPU, and the test phase can forward with CPU mode.
Some layers, e.g smoothL1, do not have the CPU implementation.

**Comment by fjfo** [comment]
Got it,
Thank you
