### ISSUE TITLE
检测错误

### ISSUE THREAD

**Issue by mychina75** [D-X-Y/caffe-faster-rcnn#8]
以为是cpu部分代码的问题，就用您提供的example下面demo_frcnn.sh，在GPU上又跑，还是不对。
因为训练是用两块GPU训的，以为是并行出的错，改成单GPU训VGG16，结果还是不对。。。
又截了个gpu测试的图，请版主看看是参数设置的问题，还是哪的原因啊，多谢！

**Comment by mychina75** [comment]
![420944a2-107a-11e7-9553-2abb4a45a9a4](https://cloud.githubusercontent.com/assets/798230/24336731/b5c9f226-12c6-11e7-8ee6-00becbc3659f.JPG)

**Comment by xwater8** [comment]
請問你在Windows上面編譯的時候有遇到類似的問題嗎??
Undefined symbols for architecture x86_64:
"FRCNN_API::Detector::predict(cv::Mat const&, std::__1::vector<caffe::Frcnn::BBox, std::__1::allocator<caffe::Frcnn::BBox > >&)", referenced from:
_main in demo_frcnn_api.o
"FRCNN_API::Detector::Set_Model(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >&)", referenced from:
_main in demo_frcnn_api.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

是如何解掉的呢？ 我已經把OpenCV換成2.4.13，一樣出現這個錯誤

**Comment by D-X-Y** [comment]
我没有在windows上用过caffe，windows也用clang编译么？

**Comment by D-X-Y** [comment]
@mychina75 抱歉这么久才回复，最近有些急事在赶，我过几天会检查下这个问题。
以前用py-faster-rcnn的模型测试过，应该是没问题的。

**Comment by mychina75** [comment]
@xwater8 看错误应该是没有找到定义Detector::predict和Detector::Set_Model函数的lib库文件（如果你单独封装了lib库），或者包含这两个函数的cpp文件没有加到VC的项目中。

@D-X-Y 谢谢回复，我找py-faster-rcnn的模型测试下。

**Comment by D-X-Y** [comment]
@mychina75 我感觉你应该是少了模型转换的步骤。
不能直接用训练的模型拿开测试，bbox prod有一个回归的过程，训练时归一化了，测试时得把归一化的均值方差恢复回去，这部分代码在我的example里也提供了。

**Comment by xwater8** [comment]
@mychina75 謝謝，關於Detector那邊已經解掉了。
現在碰到另外一個問題，我CPU版本編譯可以過，但當我要編譯GPU版本的時候會出現
![image](https://cloud.githubusercontent.com/assets/15085015/24654957/aa905ad6-196e-11e7-8b24-f96793f9d219.png)
這個問題只會發生在我編譯frcnn_proposal_layer.cu身上，有什麼好的解法嗎?

**Comment by xwater8** [comment]
@D-X-Y 這邊有個不影響程式運行的小錯誤
這個檔案在include/caffe/FRCNN/util/frcnn_gpu_nms.hpp
![image](https://cloud.githubusercontent.com/assets/15085015/24657827/6027e39a-197a-11e7-9031-9d5825a3fde7.png)

**Comment by D-X-Y** [comment]
@xwater8 多谢已经改正这个错误，这个代码需要cuda的标准库cub，是不是你在vs的动态库之类的没有添加齐？？

**Comment by xwater8** [comment]
@D-X-Y 我已經把frcnn_proposal_layer.cu解掉了，雖說不確定解法對不對，解法是將<cub.cuh>往下搬就編譯過去了，也覺得有點莫名其妙....
![image](https://cloud.githubusercontent.com/assets/15085015/24690990/5e79b04e-1a03-11e7-9f8b-7e1a7ae9af1d.png)
現在碰到另外一個問題，在準備做nms的時候會碰到vector超出界線，問題是出在這裡
![image](https://cloud.githubusercontent.com/assets/15085015/24691033/bf5eb058-1a03-11e7-94cb-269dddf8b275.png)
anchor和sorted_vector上面有做一個erase的動作，讓她們只剩下6000個，但是我這邊得到的index卻會超出這個範圍。
我的問題是，這是因為我的frcnn_porposal_layer.cu沒有弄好才發生這種情況，還是說這真的是一個當初寫程式上少考慮到的問題？

**Comment by mychina75** [comment]
@D-X-Y 楼主圣明，模型转换后就没问题了，非常感谢！

**Comment by mychina75** [comment]
@D-X-Y 还有个问题请教一下，rpn的模型也需要转换吗？不转也会有问题吧？

**Comment by D-X-Y** [comment]
@xwater8 嗷，好像是以前在debug，忘删了。。。。CU代码应该还是没问题的~

**Comment by D-X-Y** [comment]
@mychina75 RPN的模型应该是不用转换。因为是直接在layer里自己做的，不像detection最后一层转化成结果是在网络完做的。
